In [1]:
%load_ext autoreload
# reloads the file constantly so you don't need to reset
%autoreload 2 

In [2]:
%reload_ext autoreload

In [3]:
# import the libraries
from align import (
    NeedlemanWunsch,
    read_fasta)
import numpy as np
from typing import Tuple

In [4]:
scores = np.zeros([(3 + 1), (2 + 1)])
scores

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
scores[:, 0] = [-1 * i for i in range(0, 3 + 1)]
scores = np.insert(scores, [0][0], 0)
scores

array([ 0.,  0.,  0.,  0., -1.,  0.,  0., -2.,  0.,  0., -3.,  0.,  0.])

In [6]:
seq1, _ = read_fasta("./data/test_seq1.fa")
seq2, _ = read_fasta("./data/test_seq2.fa")
seq1, seq2


('MYQR', 'MQR')

In [7]:
seq3, _ = read_fasta("./data/test_seq3.fa")
seq4, _ = read_fasta("./data/test_seq4.fa")
seq3, seq4

('MAVHQLIRRP', 'MQLIRHP')

In [8]:
N_W = NeedlemanWunsch(sub_matrix_file = "./substitution_matrices/BLOSUM62.mat", gap_open = -10, gap_extend = -1)
if ('M', 'M') in N_W.sub_dict:
    # get the score for the two values, return error if not a match/mismatch
    score = (N_W.sub_dict.get(('Q', 'Q'), 'NO VALUE'))
    
score

5.0

In [9]:
N_W.align(seq1, seq2)

[[  0. -10. -11. -12. -13.]
 [-10.   5. -11. -11. -13.]
 [-11. -10.   4.  -1.  -6.]
 [-12. -12.  -8.   5.   4.]]


(4.0, 'MYQR', 'M-QR')

In [10]:
N_W.align(seq3, seq4)

[[  0. -10. -11. -12. -13. -14. -15. -16. -17. -18. -19.]
 [-10.   5. -11. -10. -14. -13. -12. -14. -17. -18. -20.]
 [-11. -10.   4.  -8.  -7.  -3. -11. -13. -10. -11. -14.]
 [-12.  -9.  -7.   5. -10.  -9.   1.  -8. -13. -12. -14.]
 [-13. -11.  -8.  -4.   2.  -9.  -5.   5. -11. -13. -14.]
 [-14. -14.  -9. -11.  -4.   3. -11.  -8.  10.  -1.  -9.]
 [-15. -16. -11. -12.   1.  -4.   0. -11.  -6.  10.  -3.]
 [-16. -17. -11. -12. -10.   0.  -7.  -3.  -9.  -3.  17.]]


(17.0, 'MAVHQLIRRP', 'M---QLIRHP')